apiVersion : v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    app: catalogue
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port